name: C++ and Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Build project
      run: |
        cmake -S . -B build
        cmake --build build

    - name: Prepare for testing
      run: cp build/cpp/_axe.so python/

    - name: Run tests
      run: |
        export PYTHONPATH=.
        python -m pytest